import type {
  StarConquestUniverseId,
  StarConquestUniverseTheme,
} from './star-conquest-universe.types';

/** Design global Star Conquest — uniquement l’univers Ruche (agent swarm). */
export const STAR_CONQUEST_UNIVERSE_ORDER: readonly StarConquestUniverseId[] = [
  'agent-swarm',
] as const;

export const DEFAULT_STAR_CONQUEST_UNIVERSE: StarConquestUniverseId = 'agent-swarm';

const UNIVERSE_STORAGE_KEY = 'star-conquest-universe';

export const STAR_CONQUEST_UNIVERSES: Record<
  StarConquestUniverseId,
  StarConquestUniverseTheme
> = {
  'stellar-nebula': {
    id: 'stellar-nebula',
    label: 'Nébuleuse Stellar',
    shortLabel: 'Nébuleuse',
    description: 'Nuages stellaires abstraits — clusters de lumière et poussière cosmique.',
    bgCenter: '#0a0618',
    bgEdge: '#1a1035',
    auroraRgb: [0.45, 0.22, 0.75],
    auroraSecondaryRgb: [0.2, 0.55, 0.85],
    peerLayout: 'nebula-cluster',
    effectKind: 'nebula-clouds',
    showConstellations: false,
    showNeuralLinks: true,
    showDepthStars: true,
    coreOpacity: 0.52,
    haloOpacity: 0.22,
    coreSizeMult: 1.15,
    haloSizeMult: 2.4,
    linkOpacity: 0.38,
    constellationOpacity: 0,
    driftSpeedMult: 0.85,
    depthFarCount: 420,
    depthMidCount: 180,
    depthNearCount: 60,
  },
  'synaptic-cortex': {
    id: 'synaptic-cortex',
    label: 'Cortex Synaptique',
    shortLabel: 'Cortex',
    description: 'Réseau neuronal pulsant — synapses et impulsions électriques entre quêtes.',
    bgCenter: '#060812',
    bgEdge: '#12102a',
    auroraRgb: [0.32, 0.9, 0.93],
    auroraSecondaryRgb: [0.65, 0.35, 0.98],
    peerLayout: 'ring',
    effectKind: 'synaptic-pulse',
    showConstellations: false,
    showNeuralLinks: true,
    showDepthStars: true,
    coreOpacity: 0.58,
    haloOpacity: 0.26,
    coreSizeMult: 1.1,
    haloSizeMult: 2.5,
    linkOpacity: 0.55,
    constellationOpacity: 0,
    driftSpeedMult: 1,
    depthFarCount: 280,
    depthMidCount: 120,
    depthNearCount: 40,
  },
  'orbital-p2p': {
    id: 'orbital-p2p',
    label: 'Anneau Orbital P2P',
    shortLabel: 'Orbital',
    description: 'Peers en orbites concentriques — sync % = rayon, latence = vitesse.',
    bgCenter: '#040810',
    bgEdge: '#0c1428',
    auroraRgb: [0.24, 0.85, 1],
    auroraSecondaryRgb: [0.15, 0.55, 0.95],
    peerLayout: 'orbital-rings',
    effectKind: 'orbital-rings',
    showConstellations: false,
    showNeuralLinks: true,
    showDepthStars: true,
    coreOpacity: 0.5,
    haloOpacity: 0.2,
    coreSizeMult: 1,
    haloSizeMult: 2.2,
    linkOpacity: 0.48,
    constellationOpacity: 0,
    driftSpeedMult: 0.75,
    depthFarCount: 200,
    depthMidCount: 80,
    depthNearCount: 30,
  },
  'm4t3r-grid': {
    id: 'm4t3r-grid',
    label: 'Grille M4T3R',
    shortLabel: 'Grille',
    description: 'Grille isométrique de récompenses — cellules lumineuses et trails dorés.',
    bgCenter: '#0a0806',
    bgEdge: '#1a1408',
    auroraRgb: [0.91, 0.72, 0.43],
    auroraSecondaryRgb: [0.55, 0.4, 0.2],
    peerLayout: 'grid',
    effectKind: 'm4t3r-grid',
    showConstellations: false,
    showNeuralLinks: true,
    showDepthStars: false,
    coreOpacity: 0.62,
    haloOpacity: 0.18,
    coreSizeMult: 1.2,
    haloSizeMult: 1.8,
    linkOpacity: 0.42,
    constellationOpacity: 0,
    driftSpeedMult: 0.65,
    depthFarCount: 0,
    depthMidCount: 0,
    depthNearCount: 0,
  },
  'zodiac-constellation': {
    id: 'zodiac-constellation',
    label: 'Constellation Zodiac',
    shortLabel: 'Zodiac',
    description: 'Cinq familles de quêtes en constellations zodiacales respirantes.',
    bgCenter: '#050510',
    bgEdge: '#0e0a22',
    auroraRgb: [0.5, 0.45, 0.85],
    auroraSecondaryRgb: [0.35, 0.75, 0.9],
    peerLayout: 'ring',
    effectKind: 'zodiac-guides',
    showConstellations: true,
    showNeuralLinks: true,
    showDepthStars: true,
    coreOpacity: 0.55,
    haloOpacity: 0.24,
    coreSizeMult: 1.05,
    haloSizeMult: 2.6,
    linkOpacity: 0.35,
    constellationOpacity: 0.18,
    driftSpeedMult: 0.9,
    depthFarCount: 500,
    depthMidCount: 200,
    depthNearCount: 80,
  },
  'p2p-aurora': {
    id: 'p2p-aurora',
    label: 'Aurore P2P',
    shortLabel: 'Aurore',
    description: 'Champ d’ondes lumineuses — peers connectés amplifient l’aurore synaptique.',
    bgCenter: '#040812',
    bgEdge: '#081828',
    auroraRgb: [0.2, 0.95, 0.65],
    auroraSecondaryRgb: [0.35, 0.55, 1],
    peerLayout: 'ring',
    effectKind: 'aurora-waves',
    showConstellations: false,
    showNeuralLinks: true,
    showDepthStars: true,
    coreOpacity: 0.48,
    haloOpacity: 0.28,
    coreSizeMult: 1,
    haloSizeMult: 2.8,
    linkOpacity: 0.4,
    constellationOpacity: 0,
    driftSpeedMult: 1.1,
    depthFarCount: 150,
    depthMidCount: 60,
    depthNearCount: 25,
  },
  'agent-swarm': {
    id: 'agent-swarm',
    label: 'Ruche Agent Swarm',
    shortLabel: 'Ruche',
    description: 'Essaims d’agents IA autour des familles — intelligence collective visible.',
    bgCenter: '#070504',
    bgEdge: '#141008',
    auroraRgb: [0.96, 0.78, 0.38],
    auroraSecondaryRgb: [0.82, 0.48, 0.18],
    peerLayout: 'swarm-orbit',
    effectKind: 'agent-swarm',
    showConstellations: false,
    showNeuralLinks: true,
    showDepthStars: true,
    coreOpacity: 0.68,
    haloOpacity: 0.14,
    coreSizeMult: 1.18,
    haloSizeMult: 2.05,
    linkOpacity: 0.28,
    constellationOpacity: 0,
    driftSpeedMult: 0.28,
    depthFarCount: 100,
    depthMidCount: 50,
    depthNearCount: 24,
  },
  'nexus-portal': {
    id: 'nexus-portal',
    label: 'Hub Nexus Portal',
    shortLabel: 'Nexus',
    description: 'Portail central — shards d’univers orbitent autour du nœud local P2P.',
    bgCenter: '#060818',
    bgEdge: '#101030',
    auroraRgb: [0.4, 0.95, 0.95],
    auroraSecondaryRgb: [0.75, 0.35, 0.95],
    peerLayout: 'ring',
    effectKind: 'nexus-portal',
    showConstellations: false,
    showNeuralLinks: true,
    showDepthStars: true,
    coreOpacity: 0.56,
    haloOpacity: 0.25,
    coreSizeMult: 1.12,
    haloSizeMult: 2.5,
    linkOpacity: 0.5,
    constellationOpacity: 0,
    driftSpeedMult: 0.95,
    depthFarCount: 320,
    depthMidCount: 140,
    depthNearCount: 50,
  },
  'conquest-timeline': {
    id: 'conquest-timeline',
    label: 'Timeline Conquête',
    shortLabel: 'Timeline',
    description: 'Axe temporel Z — quêtes passées, présentes et futures en profondeur.',
    bgCenter: '#080810',
    bgEdge: '#141028',
    auroraRgb: [0.55, 0.5, 0.95],
    auroraSecondaryRgb: [0.35, 0.8, 0.75],
    peerLayout: 'timeline-z',
    effectKind: 'timeline-axis',
    showConstellations: false,
    showNeuralLinks: true,
    showDepthStars: true,
    coreOpacity: 0.5,
    haloOpacity: 0.22,
    coreSizeMult: 1,
    haloSizeMult: 2.2,
    linkOpacity: 0.44,
    constellationOpacity: 0,
    driftSpeedMult: 0.8,
    depthFarCount: 240,
    depthMidCount: 100,
    depthNearCount: 35,
  },
  'galaxy-graph': {
    id: 'galaxy-graph',
    label: 'Galaxie Knowledge Graph',
    shortLabel: 'Galaxie',
    description: 'Spirale logarithmique — clusters peers, bras par famille, zoom macro/micro.',
    bgCenter: '#030508',
    bgEdge: '#0a0818',
    auroraRgb: [0.6, 0.35, 0.9],
    auroraSecondaryRgb: [0.25, 0.7, 0.95],
    peerLayout: 'galaxy-spiral',
    effectKind: 'galaxy-spiral',
    showConstellations: false,
    showNeuralLinks: true,
    showDepthStars: true,
    coreOpacity: 0.6,
    haloOpacity: 0.3,
    coreSizeMult: 1.18,
    haloSizeMult: 2.7,
    linkOpacity: 0.42,
    constellationOpacity: 0,
    driftSpeedMult: 0.7,
    depthFarCount: 800,
    depthMidCount: 350,
    depthNearCount: 120,
  },
};

export function starConquestUniverseTheme(
  id: StarConquestUniverseId
): StarConquestUniverseTheme {
  return STAR_CONQUEST_UNIVERSES[id];
}

export function loadStoredUniverse(): StarConquestUniverseId {
  return DEFAULT_STAR_CONQUEST_UNIVERSE;
}

export function storeUniverse(id: StarConquestUniverseId): void {
  if (typeof localStorage === 'undefined') return;
  localStorage.setItem(UNIVERSE_STORAGE_KEY, id);
}

export function nextUniverse(id: StarConquestUniverseId): StarConquestUniverseId {
  const idx = STAR_CONQUEST_UNIVERSE_ORDER.indexOf(id);
  const next = (idx + 1) % STAR_CONQUEST_UNIVERSE_ORDER.length;
  return STAR_CONQUEST_UNIVERSE_ORDER[next];
}
